Core/Piranha.Manager/Areas/Manager/Controllers/PostTypeMgrController.cs
/*
 * Piranha CMS
 * Copyright (c) 2014, Håkan Edling, All rights reserved.
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.
 */

using System;
using System.Web.Mvc;
using Piranha.Manager.Models.PostType;

namespace Piranha.Areas.Manager.Controllers
{
	/// <summary>
	/// Controller for managing post types.
	/// </summary>
	[Authorize]
	[RouteArea("Manager", AreaPrefix="manager")]
	public class PostTypeMgrController : ManagerController
	{
		/// <summary>
		/// Gets the list of the currently available post types.
		/// </summary>
		/// <returns>The view result</returns>
		[Route("posttypes")]
		public ActionResult List() {
			return View(ListModel.Get());
		}

		/// <summary>
		/// Gets the edit view for a new or existing post type.
		/// </summary>
		/// <param name="id">The optional id</param>
		/// <returns>The view result</returns>
		[Route("posttype/edit/{id:Guid?}")]
		public ActionResult Edit(Guid? id = null) {
			if (id.HasValue) {
				ViewBag.Title = Piranha.Manager.Resources.PostType.EditTitle;
				return View(EditModel.GetById(api, id.Value));
			} else {
				ViewBag.Title = Piranha.Manager.Resources.PostType.AddTitle;
				return View(new EditModel());
			}
		}

		/// <summary>
		/// Saves the given post type.
		/// </summary>
		/// <param name="model">The post type</param>
		/// <returns>The view result</returns>
		[HttpPost]
		[Route("posttype/save")]
		[ValidateAntiForgeryToken]
		public ActionResult Save(EditModel model) {
			if (ModelState.IsValid) {
				model.Save(api);
				return RedirectToAction("edit", new { id = model.Id });
			}
			if (model.Id.HasValue)
				ViewBag.Title = Piranha.Manager.Resources.PostType.EditTitle;
			else ViewBag.Title = Piranha.Manager.Resources.PostType.AddTitle;

			return View("Edit", model);
		}

		/// <summary>
		/// Deletes the post type with the given id.
		/// </summary>
		/// <param name="id">The unique id</param>
		/// <returns>The redirect result</returns>
		[Route("posttype/delete/{id:Guid}")]
		public ActionResult Delete(Guid id) {
			var type = api.PostTypes.GetSingle(where: t => t.Id == id);
			if (type != null) {
				api.PostTypes.Remove(type);
				api.SaveChanges();
			}
			return RedirectToAction("List");
		}
	}
}

Core/Piranha.Manager/Areas/Manager/Views/PostTypeMgr/Edit.cshtml
@model Piranha.Manager.Models.PostType.EditModel

@using (var form = Html.BeginForm("Save", "PostTypeMgr", FormMethod.Post, new { @class = "form", @role = "form" })) {
	@Html.AntiForgeryToken()
	@Html.HiddenFor(m => m.Id)

	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 buttons">
				<!-- Actions -->
				<div class="btn-group">
					<button type="submit" class="btn btn-labeled btn-success">
						<span class="btn-label">
							<i class="glyphicon glyphicon-ok"></i>
						</span>@Piranha.Manager.Resources.Global.Save
					</button>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12">
				<div class="form-group">
					@Html.TextBoxFor(m => m.Name, new { @class = "form-control title", @placeholder = "Add name" })
					@Html.ValidationMessageFor(m => m.Name)
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-8">
				<div class="form-group">
					@Html.TextAreaFor(m => m.Description, new { @class = "form-control count-me", @rows = 4, @placeholder = "Add optional description" })
					<p><span>@(!String.IsNullOrEmpty(Model.Description) ? Model.Description.Length : 0)</span>/255 characters</p>
					@Html.ValidationMessageFor(m => m.Description)
				</div>
			</div>
			<div class="col-sm-4">
				<div class="form-group">
					@Html.TextBoxFor(m => m.Route, new { @class = "form-control meta", @placeholder = "Add optional route" })
					@Html.ValidationMessageFor(m => m.Route)
				</div>
				<div class="form-group">
					@Html.TextBoxFor(m => m.View, new { @class = "form-control meta", @placeholder = "Add optional view" })
					@Html.ValidationMessageFor(m => m.View)
				</div>
				<div class="form-group">
					@Html.TextBoxFor(m => m.CommentRoute, new { @class = "form-control meta", @placeholder = "Add optional comment route" })
					@Html.ValidationMessageFor(m => m.CommentRoute)
				</div>
			</div>
		</div>

		<div class="panel panel-white">
			<div class="panel-body">
				<h3 class="section-title">
					Archive settings
					<span class="pull-right">
						@Html.LabelFor(m => m.EnableArchive, "Generate archive automatically", new { @class = "label-small" })
						@Html.CheckBoxFor(m => m.EnableArchive)
					</span>
				</h3>

				<div class="row">
					<!-- Post type settings -->
					<div class="col-sm-6">				
						@Html.LabelFor(m => m.ArchiveTitle, Piranha.Manager.Resources.PostType.ArchiveTitle)
						<div class="form-group">
							@Html.TextBoxFor(m => m.ArchiveTitle, new { @class = "form-control meta", @placeholder = "Add archive title" })
							@Html.ValidationMessageFor(m => m.ArchiveTitle)
						</div>
						@Html.LabelFor(m => m.Slug, Piranha.Manager.Resources.Global.Slug)
						<div class="form-group">
							@Html.TextBoxFor(m => m.Slug, new { @class = "form-control meta", @placeholder = "A slug will be generated automatically" })
							@Html.ValidationMessageFor(m => m.Slug)
						</div>
						@Html.LabelFor(m => m.ArchiveRoute, Piranha.Manager.Resources.PostType.ArchiveRoute)
						<div class="form-group">
							@Html.TextBoxFor(m => m.ArchiveRoute, new { @class = "form-control meta", @placeholder = "Add optional archive route" })
							@Html.ValidationMessageFor(m => m.ArchiveRoute)
						</div>
						@Html.LabelFor(m => m.ArchiveView, Piranha.Manager.Resources.PostType.ArchiveView)
						<div class="form-group">
							@Html.TextBoxFor(m => m.ArchiveView, new { @class = "form-control meta", @placeholder = "Add optional archive view" })
							@Html.ValidationMessageFor(m => m.ArchiveView)
						</div>
					</div>

					<!-- Archive settings -->
					<div class="col-sm-6">
						@Html.LabelFor(m => m.MetaKeywords, Piranha.Manager.Resources.Global.MetaKeywords)
						<div class="form-group">
							@Html.TextBoxFor(m => m.MetaKeywords, new { @class = "form-control meta", @placeholder = "Add archive meta keywords" })
							@Html.ValidationMessageFor(m => m.MetaKeywords)
						</div>
						@Html.LabelFor(m => m.MetaDescription, Piranha.Manager.Resources.Global.MetaDescription)
						<div class="form-group">
							@Html.TextAreaFor(m => m.MetaDescription, new { @class = "form-control meta count-me", @rows = 7, @style = "height:164px", @placeholder = "Add archive meta description" })
							<p><span>@(!String.IsNullOrEmpty(Model.MetaDescription) ? Model.MetaDescription.Length : 0)</span>/255 characters</p>
							@Html.ValidationMessageFor(m => m.MetaDescription)
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
}

Core/Piranha.Manager/Areas/Manager/Views/PostTypeMgr/List.cshtml
@model Piranha.Manager.Models.PostType.ListModel
@{
	ViewBag.Title = Piranha.Manager.Resources.PostType.ListTitle;
}
@section script {
	<script type="text/javascript">
		var options = {
			valueNames: ['type-name', 'type-updated', 'type-created']
		};
		var typeList = new List('type-list', options);
	</script>
}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 buttons">
			<div class="btn-group">
				<a href="@Url.Action("Edit", new { @id = "" })" class="btn btn-primary btn-labeled">
					<span class="btn-label">
						<i class="glyphicon glyphicon-plus"></i>
					</span>@Piranha.Manager.Resources.Global.Add
				</a>
			</div>
		</div>
	</div>

	<table id="type-list" class="table table-striped table-main">
		<thead>
			<tr>
				<th><span class="sort desc" data-sort="type-name">@Piranha.Manager.Resources.Global.Name</span></th>
				<th class="date"><span class="sort" data-sort="type-updated">@Piranha.Manager.Resources.Global.Updated</span></th>
				<th class="date"><span class="sort" data-sort="type-created">@Piranha.Manager.Resources.Global.Created</span></th>
				<th class="actions one"></th>
			</tr>
		</thead>
		<tbody class="list">
			@foreach (var type in Model.Items) {
				<tr>
					<td class="type-name"><a href="@Url.Action("Edit", new { @id = type.Id })">@type.Name</a></td>
					<td class="type-updated">@type.Updated.ToString("yyyy-MM-dd")</td>
					<td class="type-created">@type.Created.ToString("yyyy-MM-dd")</td>
					<td class="actions">
						<a class="delete" href="@Url.Action("Delete", new { @id = type.Id })"></a>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>